site_name: Hedera Connector
site_description: "Documentation for the Hedera Connector microservice"
repo_url: https://github.com/isrand/hedera-connector
extra_css:
    - css/css.css
nav:
    - Home: index.md
    - ğŸ› ï¸ Setup:
        - From source code: setup/source.md
    - ğŸ“– Reference:
        - API: reference/api.md

theme:
  name: readthedocs
  prev_next_buttons_location: hidden
  titles_only: false
  site_name: Hedera Connector
  include_homepage_in_sidebar: true
  logo: img/logo.png
markdown_extensions:
  - markdown.extensions.admonition
plugins:
  - open-in-new-tab
  - swagger-ui-tag
